services:
  - type: web
    name: pc-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /api/event-history
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: APP_ALLOWED_ORIGINS
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PORT
        value: 465
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: APP_EMAIL
        sync: false
      - key: CALLBACK_URL
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: APP_UPLOAD_DIR
        value: /data/uploads
    disk:
      name: uploads
      mountPath: /data
      sizeGB: 1