spring.datasource.url=${SPRING_DATASOURCE_URL:${JDBC_DATABASE_URL:}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${JDBC_DATABASE_USERNAME:}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${JDBC_DATABASE_PASSWORD:}}