spring.application.name=pc_backend

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/oroye_campaign
spring.datasource.username=root
spring.datasource.password=Aaliyah@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

spring.mail.host = smtp.gmail.com
spring.mail.port = 465
spring.mail.username = oroye.campaign@gmail.com
spring.mail.password = myajakjayvcopbch
smtp.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.properties.mail.smtp.ssl.enable = true

app.email = oroye.campaign@gmail.com

callback_url=http://localhost:3000/payment-success

secret_key=sk_test_0b11d8bcbb96257f11f39697ffe2ca3f5e7129da

jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400000